### ISSUE TITLE
部署报错呀，谁知道是啥原因呀？

### ISSUE THREAD

**Issue by enshui** [linyuxuanlin/Markdown-CV-Site#1]
按照步骤一步步来，报错了
<img width="598" alt="1" src="https://github.com/linyuxuanlin/Markdown-CV-Site/assets/30564129/19382612-5e4f-49bc-a32e-d142dec2c70c">

<img width="580" alt="2" src="https://github.com/linyuxuanlin/Markdown-CV-Site/assets/30564129/bd0f5591-16ac-4c06-86ae-3539c3f25b43">

**Comment by enshui** [comment]
<img width="781" alt="image" src="https://github.com/linyuxuanlin/Markdown-CV-Site/assets/30564129/0b04c61c-1ccc-4867-a1d5-8f3d00bfe274">

**Comment by linyuxuanlin** [comment]
MarkCV 在 npm 18 出现了版本不兼容的情况，当前版本已解决，请参考 readme 提供的方法进行部署。
